name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - hydra-core=1.3.2
  - matplotlib=3.8.2
  - pandas=2.1.3
  - pip=23.3.1
  - scikit-learn=1.3.2
  - numpy=1.26.3
  - mlflow
  - wandb
  - pydantic_settings=2.2.1
  - pandas_profiling=3.6.6
  - ydata_profiling=4.6.4
  - ipywidgets=8.1.2
  - pip:
      - mlflow
      - wandb
