name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.5
  - pandas=2.1.4
  - pytest=8.0.1
  - scipy=1.11.4
  - pip=23.3.1
  - pip:
      - mlflow==2.9.2
      - wandb==0.16.2
